name: Deploy

on: 
  repository_dispatch:
    types: [trigger-deploy]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa #optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
          if_key_exists: fail
      - name: Deploy
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd deployment && docker pull haristhohir/gate:latest && docker compose up -d"
