name: Deploy

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa #optional
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: fail
